import { Inter } from "next/font/google";
import "@/styles/globals.css";
// ! redux
import ReduxProvider from "./redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "final-project-backup",
  description: "Generated by Shadow",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
