import { Roboto } from "next/font/google";
import "@/styles/globals.css";
// ! redux

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "700"] });
export const metadata = {
  title: "final-project-backup",
  description: "Generated by Shadow",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
